const products={easy:{name:'Easy elektriskt',category:'Höj- & sänkbart skrivbord',price:2645,image:'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=90',description:'Ett rent och robust höj- och sänkbart skrivbord som följer din arbetsdag.'},caen:{name:'Caen kontorsstol',category:'Ergonomi',price:985,image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=85',description:'Ergonomisk komfort i ett avskalat uttryck. För fokus som håller hela dagen.'},cabinet:{name:'Småland skjutdörrskåp',category:'Förvaring',price:4595,image:'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?auto=format&fit=crop&w=900&q=85',description:'Rumsren förvaring med skjutdörrar, hjul och gott om plats för vardagens ordning.'},manacor:{name:'Manacor barstol',category:'Sittning',price:550,image:'https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=900&q=85',description:'Lätt, stapelbar och tidlös. En praktisk favorit för pausrum och mötesplatser.'}};
let selectedId='caen',selectedQty=1,cart=JSON.parse(localStorage.getItem('smalands-cart')||'[]');const money=n=>new Intl.NumberFormat('sv-SE').format(n)+' kr',overlay=document.querySelector('#overlay'),closeAll=()=>{document.querySelectorAll('.modal,.drawer').forEach(x=>{x.classList.remove('is-open');x.setAttribute('aria-hidden','true')});overlay.hidden=true;document.body.classList.remove('locked')};
function openPanel(id){overlay.hidden=false;document.body.classList.add('locked');const panel=document.querySelector(id);panel.classList.add('is-open');panel.setAttribute('aria-hidden','false')}
function renderCart(){const area=document.querySelector('#cart-items'),count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+x.qty*x.price,0);document.querySelector('#cart-count').textContent=count;document.querySelector('#cart-total').textContent=money(total);area.innerHTML=cart.length?cart.map((x,i)=>`<article class="cart-line"><img src="${x.image}" alt=""><div><p>${x.category}</p><strong>${x.name}</strong><span>${money(x.price)}</span><div class="line-actions"><button data-line="${i}" data-change="-1">−</button><b>${x.qty}</b><button data-line="${i}" data-change="1">+</button><button class="remove" data-line="${i}" data-change="remove">Ta bort</button></div></div></article>`).join(''):'<p class="empty-cart">Din cart är tom.</p>';localStorage.setItem('smalands-cart',JSON.stringify(cart))}
function preview(id){selectedId=id;selectedQty=1;const p=products[id];document.querySelector('#preview-image').src=p.image;document.querySelector('#preview-image').alt=p.name;document.querySelector('#preview-category').textContent=p.category;document.querySelector('#preview-name').textContent=p.name;document.querySelector('#preview-description').textContent=p.description;document.querySelector('#preview-price').textContent=money(p.price)+' exkl. moms';document.querySelector('#quantity').textContent=selectedQty;openPanel('#product-modal')}
function toast(message='Tillagd i din cart'){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelector('.cart-trigger').addEventListener('click',()=>{renderCart();openPanel('#cart-drawer')});document.querySelector('.login-trigger').addEventListener('click',()=>openPanel('#login-modal'));document.querySelectorAll('.preview-trigger').forEach(x=>x.addEventListener('click',()=>preview(x.dataset.product)));document.querySelectorAll('.close-panel').forEach(x=>x.addEventListener('click',closeAll));overlay.addEventListener('click',closeAll);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});
document.querySelector('#increase').addEventListener('click',()=>{selectedQty++;document.querySelector('#quantity').textContent=selectedQty});document.querySelector('#decrease').addEventListener('click',()=>{selectedQty=Math.max(1,selectedQty-1);document.querySelector('#quantity').textContent=selectedQty});document.querySelector('#add-cart').addEventListener('click',()=>{const p=products[selectedId],line=cart.find(x=>x.id===selectedId);line?line.qty+=selectedQty:cart.push({id:selectedId,qty:selectedQty,...p});renderCart();closeAll();toast()});
document.querySelector('#cart-items').addEventListener('click',e=>{const b=e.target.closest('button[data-line]');if(!b)return;const i=Number(b.dataset.line),change=b.dataset.change;if(change==='remove')cart.splice(i,1);else{cart[i].qty+=Number(change);if(cart[i].qty<1)cart.splice(i,1)}renderCart()});document.querySelector('#login-form').addEventListener('submit',e=>{e.preventDefault();closeAll();document.querySelector('.login-trigger').textContent='Mitt konto';toast('Inloggning lyckades')});renderCart();
