const products={
  x50:{name:'X50 stapelbar stol',category:'Stolar',price:1795,image:'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=900&q=85',description:'En stabil och elegant stol för mötesrum, matsal och event.',details:['Stapelbar upp till 10 stolar','Tåligt pulverlackerat stativ','Passar offentlig miljö']},
  foldTable:{name:'Kvadrat fällbart bord',category:'Bord',price:2495,image:'https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=900&q=85',description:'Ett flexibelt bord som snabbt skapar plats för många.',details:['160 × 80 cm','Fällbart benstativ','Slitstark laminatskiva']},
  cafe:{name:'Café Rund',category:'Bord',price:1695,image:'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=900&q=85',description:'Ett litet, robust cafébord för samtal och pauser.',details:['Ø 70 cm','Svart stålstativ','För inom- och utomhusbruk']},
  conference:{name:'Forma konferensbord',category:'Bord',price:6495,image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=85',description:'Ett generöst konferensbord som samlar teamet.',details:['220 × 100 cm','Kabelgenomföring ingår','Massiv ekfanér']},
  desk:{name:'Easy höj- & sänkbart bord',category:'Kontorsmöbler',price:2645,image:'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=85',description:'Ett rent och robust skrivbord som följer din arbetsdag.',details:['Elektrisk höjd 65–130 cm','160 × 80 cm','Tyst motor med minnesfunktion']},
  officeChair:{name:'Lyon kontorsstol',category:'Kontorsmöbler',price:3395,image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=85',description:'Ergonomisk komfort och avskalat uttryck för fokuserade dagar.',details:['Justerbart svankstöd','Andningsaktiv mesh','Aluminiumkryss med hjul']},
  screen:{name:'Silencio bordsskärm',category:'Kontorsmöbler',price:725,image:'https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=900&q=85',description:'En ljuddämpande skärm som skapar lugn vid arbetsplatsen.',details:['Ljudabsorberande kärna','Flera färger','Fästen ingår']},
  cabinet:{name:'Skjutdörrskåp Ek',category:'Förvaring',price:2445,image:'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=900&q=85',description:'Rumsren, låsbar förvaring med gott om plats för vardagens ordning.',details:['80 × 40 × 72 cm','Två justerbara hyllplan','Lås med två nycklar']},
  tower:{name:'Towerförvaring',category:'Förvaring',price:3195,image:'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=900&q=85',description:'Smidig personlig förvaring intill skrivbordet.',details:['Låda och öppet fack','Låsbart','Hjul för enkel flytt']},
  barrier:{name:'Royal köstolpe',category:'Avspärrning',price:595,image:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=85',description:'En stilren köstolpe för tydliga och välkomnande flöden.',details:['Rostfritt stål','Band på 2 meter','Tung, stabil fot']},
  entrance:{name:'Entrépaket Mässing',category:'Avspärrning',price:4495,image:'https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=900&q=85',description:'En komplett entrélösning som ramar in ditt event.',details:['4 stolpar med rött rep','Mässingsfinish','För fest och offentlig miljö']},
  cart:{name:'Vagn X50',category:'Vagnar',price:4495,image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=85',description:'Gör transport och förvaring av stolar enkel.',details:['Rymmer 25 X50-stolar','Lättrullande hjul','Pulverlackerat stål']},
  textile:{name:'Duk Linne',category:'Textilier',price:495,image:'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=900&q=85',description:'En mjuk textil som ger dukningen en omsorgsfull känsla.',details:['140 × 250 cm','Tvättbar bomullsblandning','Flera kulörer']}
};
const ranges={newProducts:['cart','x50','foldTable','officeChair'],tables:['foldTable','cafe','conference'],office:['desk','officeChair','screen'],storage:['cabinet','tower'],event:['barrier','entrance','x50'],other:['textile','cart','foldTable']};
const money=n=>new Intl.NumberFormat('sv-SE').format(n)+' kr';let selectedId='x50',selectedQty=1,cart=JSON.parse(localStorage.getItem('smalands-cart')||'[]');const overlay=document.querySelector('#overlay');
const productCard=id=>{const p=products[id];return `<article class="product"><div class="product-img"><img src="${p.image}" alt="${p.name}"><button class="preview-trigger" data-product="${id}" type="button" aria-label="Visa ${p.name}">+</button></div><p class="product-tag">${p.category}</p><h3>${p.name}</h3><p class="price">${money(p.price)} <small>exkl. moms</small></p></article>`};
document.querySelector('#new-products').innerHTML=ranges.newProducts.map(productCard).join('');document.querySelectorAll('[data-range]').forEach(el=>el.innerHTML=ranges[el.dataset.range].map(productCard).join(''));
function closeAll(){document.querySelectorAll('.modal,.drawer').forEach(x=>{x.classList.remove('is-open');x.setAttribute('aria-hidden','true')});overlay.hidden=true;document.body.classList.remove('locked')};function openPanel(id){overlay.hidden=false;document.body.classList.add('locked');const panel=document.querySelector(id);panel.classList.add('is-open');panel.setAttribute('aria-hidden','false')};
function renderCart(){const area=document.querySelector('#cart-items'),count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+x.qty*x.price,0);document.querySelector('#cart-count').textContent=count;document.querySelector('#cart-total').textContent=money(total);area.innerHTML=cart.length?cart.map((x,i)=>`<article class="cart-line"><img src="${x.image}" alt=""><div><p>${x.category}</p><strong>${x.name}</strong><span>${money(x.price)}</span><div class="line-actions"><button data-line="${i}" data-change="-1">−</button><b>${x.qty}</b><button data-line="${i}" data-change="1">+</button><button class="remove" data-line="${i}" data-change="remove">Ta bort</button></div></div></article>`).join(''):'<p class="empty-cart">Din cart är tom.</p>';localStorage.setItem('smalands-cart',JSON.stringify(cart))};
function preview(id){selectedId=id;selectedQty=1;const p=products[id];for(const [key,value] of Object.entries({category:p.category,name:p.name,description:p.description,price:money(p.price)+' exkl. moms'}))document.querySelector('#preview-'+key).textContent=value;document.querySelector('#preview-image').src=p.image;document.querySelector('#preview-image').alt=p.name;document.querySelector('#preview-details').innerHTML=p.details.map(d=>`<li>${d}</li>`).join('');document.querySelector('#quantity').textContent=1;openPanel('#product-modal')};
function toast(message='Tillagd i din cart'){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function renderSearch(query=''){const clean=query.trim().toLocaleLowerCase('sv-SE'),matches=Object.entries(products).filter(([,p])=>!clean||`${p.name} ${p.category} ${p.description} ${p.details.join(' ')}`.toLocaleLowerCase('sv-SE').includes(clean));document.querySelector('#search-count').textContent=clean?`${matches.length} ${matches.length===1?'produkt':'produkter'} hittades`:'';document.querySelector('#search-results').innerHTML=matches.map(([id,p])=>`<button class="search-result preview-trigger" data-product="${id}" type="button"><img src="${p.image}" alt=""><span><small>${p.category}</small><strong>${p.name}</strong><em>${money(p.price)} exkl. moms</em></span><b>→</b></button>`).join('')||'<p class="no-results">Inga produkter matchar din sökning.</p>'}
function openSearch(){renderSearch();openPanel('#search-modal');setTimeout(()=>document.querySelector('#product-search').focus(),50)}
document.addEventListener('click',e=>{const trigger=e.target.closest('.preview-trigger');if(trigger){if(trigger.closest('#search-results'))closeAll();preview(trigger.dataset.product)}});document.querySelector('.cart-trigger').onclick=()=>{renderCart();openPanel('#cart-drawer')};document.querySelector('.login-trigger').onclick=()=>openPanel('#login-modal');document.querySelector('.mobile-login-trigger').onclick=()=>{nav.classList.remove('is-open');menu.textContent='☰';openPanel('#login-modal')};document.querySelectorAll('.close-panel').forEach(x=>x.onclick=closeAll);overlay.onclick=closeAll;document.querySelector('.search-trigger').onclick=openSearch;document.querySelector('#product-search').oninput=e=>renderSearch(e.target.value);
document.querySelector('#increase').onclick=()=>{selectedQty++;document.querySelector('#quantity').textContent=selectedQty};document.querySelector('#decrease').onclick=()=>{selectedQty=Math.max(1,selectedQty-1);document.querySelector('#quantity').textContent=selectedQty};document.querySelector('#add-cart').onclick=()=>{const p=products[selectedId],line=cart.find(x=>x.id===selectedId);line?line.qty+=selectedQty:cart.push({id:selectedId,qty:selectedQty,...p});renderCart();closeAll();toast()};document.querySelector('#cart-items').onclick=e=>{const b=e.target.closest('button[data-line]');if(!b)return;const i=+b.dataset.line;b.dataset.change==='remove'?cart.splice(i,1):(cart[i].qty+=+b.dataset.change,cart[i].qty<1&&cart.splice(i,1));renderCart()};document.querySelector('#login-form').onsubmit=e=>{e.preventDefault();closeAll();document.querySelector('.login-trigger').textContent='Mitt konto';toast('Inloggning lyckades')};
const menu=document.querySelector('.menu'),nav=document.querySelector('#main-nav'),collections=document.querySelector('#collection-menu'),toggle=document.querySelector('.collection-toggle'),header=document.querySelector('.nav');
function setCollections(open){collections.hidden=!open;toggle.setAttribute('aria-expanded',open);toggle.querySelector('span').textContent=open?'−':'+'}
toggle.onclick=e=>{e.preventDefault();setCollections(collections.hidden)};
toggle.onmouseenter=()=>{if(window.matchMedia('(min-width: 761px)').matches)setCollections(true)};
header.onmouseleave=()=>{if(window.matchMedia('(min-width: 761px)').matches)setCollections(false)};
menu.onclick=()=>{const open=!nav.classList.contains('is-open');nav.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',open);menu.textContent=open?'×':'☰'};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAll();setCollections(false);nav.classList.remove('is-open');menu.textContent='☰'}});renderCart();
